####################################################################################
# BASIC SETTINGS
####################################################################################

#
# Location of your qooxdoo distribution
# Could be relative from this location or absolute
#
QOOXDOO_PATH = PATH_TO_QOOXDOO

#
# The same as above, but from the webserver point of view
# Starting point is the application HTML file of the source folder.
# In most cases just add a "/.." compared to above
#
QOOXDOO_URI = URI_TO_QOOXDOO

#
# Namespace of your application e.g. custom
#
PROJECT_NAMESPACE = custom

#
# Titles used in your API viewer and during the build process
#
PROJECT_MAKE_TITLE = CUSTOM
PROJECT_API_TITLE = Custom

#
# Additional files (space separated list)
#
PROJECT_FILES = index.html

#
# Locales to build (space separated list)
#
PROJECT_LOCALES =






####################################################################################
# ADVANCED SETTINGS
####################################################################################

#
# Please take a look at $(QOOXDOO)/frontend/framework/tool/make/project.mk
# for more options
#







####################################################################################
# INCLUDE CORE
####################################################################################

include $(QOOXDOO_PATH)/frontend/framework/tool/make/targets.mk
include $(QOOXDOO_PATH)/frontend/framework/tool/make/project.mk
