####################################################################################
# BASIC SETTINGS
####################################################################################

#
# Location of your qooxdoo distribution
# Could be relative from this location or absolute
#
QOOXDOO_PATH = ../../..

#
# The same as above, but from the webserver point of view
# Starting point is the application HTML file of the source folder.
# In most cases just add a "/.." compared to above
#
QOOXDOO_URI = ../../../..

#
# Namespace of your application e.g. custom
#
PROJECT_NAMESPACE = qx

#
# Titles used in your API viewer and during the build process
#
PROJECT_MAKE_TITLE = FRAMEWORK
PROJECT_API_TITLE = Framework





####################################################################################
# ADVANCED SETTINGS
####################################################################################

#
# Build the whole framework
#
PROJECT_COMPLETE_BUILD = true





####################################################################################
# INCLUDE CORE
####################################################################################

include $(QOOXDOO_PATH)/frontend/framework/tool/make/targets.mk
include $(QOOXDOO_PATH)/frontend/framework/tool/make/project.mk
