version: 3

# see https://docs.pullapprove.com/config/groups/
groups:
  # documentation and tests: only 2 approvals necessary
  documentation:
    conditions:
      - "files.include('docs/*.md') or files.include('documentation/*')"
      - "not (files.exclude('docs/*.md') and files.exclude('documentation/*'))"
    reviews:
      required: 2  # 2 approvals from this group are required
      request: 2  # 2 review request will be sent at a time
      request_order: shuffle  # reviewers will be chosen in a random order
    reviewers:
      teams:
        - "PR Mergers"

  # default procedure: 5 approvals required
  default:
    conditions:
      # this group is asked to review if no previous groups match this PR
      - "not groups.active"
    reviews:
      required: 5
      request: 5
    reviewers:
      teams:
        - "PR Mergers"

# see https://docs.pullapprove.com/config/pullapprove-conditions/
pullapprove_conditions:
  # only start review process when the tests have passed
  - condition: "'*travis*' in statuses.successful"
    unmet_status: "failure"
    explanation: "Tests must pass before review starts"
    # do not review work in progress
  - condition: "'WIP' in title"
    unmet_status: pending
    explanation: "Work in progress"

notifications:
  - when: pull_request.opened
    if: "author_association == 'FIRST_TIME_CONTRIBUTOR'"
    comment: |
      Hey @{{ author }}, thanks for the PR! The review will start once
      the tests and CI checks have passed. If they don't, please review
      the logs and try to fix the issues (ask for help if you can't
      figure it out). A reviewer will be assigned once the tests are
      passing and they'll walk you through getting the PR finished
      and merged.
