version: 3

# see https://docs.pullapprove.com/config/groups/
groups:
  documentation:
    description: documentation changes require 2 approvals
    conditions:
      - '"docs/*" in files'
    reviews:
      required: 2  # 2 approvals from this group are required
      request: 5  # 5 review request will be sent at a time
    reviewers:
      teams:
        - pr-reviewers

  hotfix:
    description: urgent hotfix; 2 approvals necessary
    conditions:
      - '"hotfix" in labels'
    reviews:
      required: 2
      request: 5
    reviewers:
      teams:
        - pr-reviewers

  default:
    description: default procedure; 5 approvals required
    conditions:
      # this group is asked to review if no previous groups match this PR
      - not groups.active
    reviews:
      required: 5
      request: 5
    reviewers:
      teams:
        - pr-reviewers

# see https://docs.pullapprove.com/config/pullapprove-conditions/
pullapprove_conditions:
  - condition: 'base.ref == "master"'
    unmet_status: success
    explanation: "Review not required unless merging to master"
  - condition: 'not draft'
    unmet_status: pending
    explanation: "Work in progress, not to be reviewed yet"

notifications:
  - when: pull_request.opened
    if: 'author_association == "FIRST_TIME_CONTRIBUTOR"'
    comment: |
      Hey @{{ author }}, thanks for the PR! The review will start once
      the tests and CI checks have passed. If they don't, please review
      the logs and try to fix the issues (ask for help if you can't
      figure it out). A reviewer will be assigned once the tests are
      passing and they'll walk you through getting the PR finished
      and merged.
