import babelParser from "@babel/eslint-parser";
import qxBrowserConfig from "@qooxdoo/eslint-config-qx/browser.js";

export default [
  {
    ignores: [
      "bin/**",
      "bootstrap/**",
      "compiled/**",
      "docs/**",
      "known-good/**", 
      "node_modules/**",
      "test/**",
      "source/boot/**",
      "source/resource/**",
      "source/translation/**",
      "compile.js",
      "*.config.*"
    ]
  },
  ...qxBrowserConfig,
  {
    linterOptions: {
      reportUnusedDisableDirectives: false
    },
    languageOptions: {
      parser: babelParser,
      parserOptions: {
        ecmaVersion: 2020,
        requireConfigFile: false,
        babelOptions: {
          presets: ["@babel/preset-env"],
          plugins: ["@babel/plugin-syntax-jsx"]
        }
      },
      globals: {
        loadSass: "readonly"
      }
    },
    rules: {
      // JSDoc rules disabled for compatibility
      "jsdoc/check-alignment": "off",
      "jsdoc/check-examples": "off", 
      "jsdoc/check-indentation": "off",
      "jsdoc/check-param-names": "off",
      "jsdoc/check-syntax": "off",
      "jsdoc/check-tag-names": "off",
      "jsdoc/check-types": "off",
      "jsdoc/implements-on-classes": "off",
      "jsdoc/match-description": "off",
      "jsdoc/newline-after-description": "off",
      "jsdoc/no-types": "off",
      "jsdoc/no-undefined-types": "off",
      "jsdoc/require-description": "off",
      "jsdoc/require-description-complete-sentence": "off",
      "jsdoc/require-example": "off",
      "jsdoc/require-hyphen-before-param-description": "off",
      "jsdoc/require-jsdoc": "off",
      "jsdoc/require-param": "off",
      "jsdoc/require-param-description": "off",
      "jsdoc/require-param-name": "off",
      "jsdoc/require-param-type": "off",
      "jsdoc/require-returns": "off",
      "jsdoc/require-returns-check": "off",
      "jsdoc/require-returns-description": "off",
      "jsdoc/require-returns-type": "off",
      "jsdoc/valid-types": "off",
      
      // Qooxdoo specific overrides
      "@qooxdoo/qx/no-illegal-private-usage": "off",
      "@qooxdoo/qx/no-refs-in-members": "off",
      "no-undef": "off",
      "no-duplicate-case": "off",
      "handle-callback-err": "off",
      "no-undef-init": "off",
      "comma-dangle": "off",
      "no-array-constructor": "off",
      "no-regex-spaces": "off",
      "no-new-object": "off",
      "no-global-assign": "off",
      "no-extra-boolean-cast": "off",
      "no-new": "off",
      "no-unused-vars": "off",
      "no-eval": "off",
      "new-cap": "off",
      "no-proto": "off",
      "no-extend-native": "off",
      "no-self-compare": "off",
      "no-new-wrappers": "off",
      "wrap-iife": "off",
      "brace-style": "off",
      "dot-location": "off",
      "keyword-spacing": "off",
      "space-in-parens": "off",
      "comma-spacing": "off",
      "padded-blocks": "off",
      "space-before-blocks": "off",
      "one-var-declaration-per-line": "off",
      "semi-spacing": "off",
      "block-spacing": "off",
      "no-floating-decimal": "off",
      "computed-property-spacing": "off",
      "switch-colon-spacing": "off",
      "yoda": "off",
      "no-whitespace-before-property": "off",
      "no-extra-bind": "off",
      "space-unary-ops": "off",
      "operator-assignment": "off",
      "eol-last": "off",
      "linebreak-style": "off",
      "no-unsafe-negation": "off",
      "new-parens": "off",
      "semi": "off",
      "curly": "error",
      "no-mixed-spaces-and-tabs": "off",
      "no-extra-semi": "off",
      "indent": "off",
      "no-warning-comments": "off",
      "no-lonely-if": "off",
      "guard-for-in": "off",
      "max-params": "off",
      "no-nested-ternary": "off",
      "no-multi-spaces": "off",
      "quotes": "off",
      "no-redeclare": "off",
      "operator-linebreak": "off",
      "no-eq-null": "off",
      "no-useless-call": "off",
      "consistent-return": "off",
      "max-statements-per-line": "off",
      "no-prototype-builtins": "off",
      "array-callback-return": "off",
      "no-constant-condition": "off",
      "no-empty": "off",
      "no-fallthrough": "off",
      "valid-typeof": "off",
      "no-cond-assign": "off",
      "no-else-return": "off",
      "no-unneeded-ternary": "off",
      "one-var": "off",
      "no-useless-concat": "off",
      "no-unmodified-loop-condition": "off",
      "func-call-spacing": "off",
      "no-unexpected-multiline": "off",
      "no-labels": "off",
      "no-inner-declarations": "off",
      "no-console": "off",
      "no-implicit-globals": "off"
    }
  }
];