####################################################################################
# BASIC SETTINGS
####################################################################################

#
# Location of your qooxdoo distribution
# Could be relative from this location or absolute
#
QOOXDOO_PATH = ../../../..

#
# The same as above, but from the webserver point of view
# Starting point is the application HTML file of the source folder.
# In most cases just add a "/.." compared to above
#
QOOXDOO_URI = ../../../../..

#
# Namespace of your application e.g. custom
#
PROJECT_NAMESPACE = custom

#
# Titles used in your API viewer and during the build process
#
PROJECT_MAKE_TITLE = CUSTOM
PROJECT_API_TITLE = Custom

#
# Additional files (space separated list)
#
PROJECT_FILES = index.html

#
# Locales to build (space separated list)
#
PROJECT_LOCALES =






####################################################################################
# INCLUDE CORE
####################################################################################

#
# Include project core handling
#
include $(QOOXDOO_PATH)/frontend/framework/tool/make/project.mk

#
# Include default targets: build, source, clean, ...
#
include $(QOOXDOO_PATH)/frontend/framework/tool/make/targets.mk

#
# Include implementation targets
#
include $(QOOXDOO_PATH)/frontend/framework/tool/make/impl.mk
