<?xml version="1.0"?>
<!-- **************************************************************************
*
*  qooxdoo - the new era of web development
*
*  http://qooxdoo.org
*
*  Copyright:
*    2007 1&1 Internet AG, Germany, http://www.1und1.de
*
*  License:
*    LGPL: http://www.gnu.org/licenses/lgpl.html
*    EPL: http://www.eclipse.org/org/documents/epl-v10.php
*    See the LICENSE file in the project's top-level directory for details.
*
*  Authors:
*    * Thomas Herchenroeder (thron7)
*
**************************************************************************** -->
<!-- **************************************************************************
* NAME
*  makefile_doc.xsl -  transform qooxdoo Makefile XML to DocuWiki qooxdoo-style
*                      markup
*  
* SYNTAX
*  xsltproc makefile_doc.xsl <file>.xml
*  
*  <file>.xml  - An XML file of the format as generated by
*                tool/make/makefile_doc.py
*  
* DESCRIPTION
*  This XSLT transforms the XML representing qooxdoo makefile contents
*  (specifically application.mk) into a markup usable in the qooxdoo wiki, to
*  document the settings there.
*
* CAVEATS
* - The transformation is kept general, and does not deliver a cut-and-paste
*   content of the current wiki page; you might want to post-process the
*   resulting data. Currently, the following changes are made by hand:
*   - cut everything before "REQUIRED SETTINGS"
*   - cut everything including and after "INCLUDE EXTERNAL MAKEFILES"
*   In the existing wiki page:
*   - retain the introduction (the part before the real data starts)
*   - update the "version" entry to the current svn version of application.mk
*
* SEE ALSO
*    makefile_doc.py
**************************************************************************** -->

<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<!--
	<xsl:output method="text"/>
-->

	<xsl:template match="mak">
	  <xsl:apply-templates select="part"/>
	</xsl:template>

	<xsl:template match="part">
	  <xsl:text>=====</xsl:text>
	  <xsl:value-of select="title"/> 
	  <xsl:text> =====&#xa;&#xa;</xsl:text>
      <xsl:apply-templates select="section"/>
	  <xsl:apply-templates select="incl"/>
	</xsl:template>

	<xsl:template match="section">
		  <xsl:apply-templates select="var"/>
    	  <xsl:element name="note">
			  <xsl:value-of select="descr"/>
    	  </xsl:element>
		  <xsl:text>&#xa;&#xa;</xsl:text>
	</xsl:template>

	<xsl:template match="var">
		  <xsl:text>==== </xsl:text>
		  <xsl:value-of select="name"/> 
		  <xsl:text> ====&#xa;&#xa;</xsl:text>
		  <!-- xsl:value-of select="name"/ --> 
    	  <xsl:text>default:     ''</xsl:text>
		  <xsl:value-of select="default"/> 
    	  <xsl:text>''&#xa;&#xa;</xsl:text>
	</xsl:template>
	
	<xsl:template match="incl">
		<xsl:value-of select="."/>
	    <xsl:text>&#xa;</xsl:text>
	</xsl:template>

	
</xsl:stylesheet>
