#
# New all target
#
all:
	@echo 
	@echo "****************************************************************************"
	@echo "  GENERATING FRAMEWORK"
	@echo "****************************************************************************"
	@echo ""
	@echo "  WARNING"
	@echo "----------------------------------------------------------------------------"
	@echo "  * The generation of the framework has been moved."
	@echo "    - Please execute your make command in frontend/project/framework"

source: all
build: all
api: all
pretty: all
fix: all

clean:
  @rm -rf .cache
  @rm -rf source/translation/messages.pot
  @rm -rf source/class/qx/locale/data
  @rm -rf source/class/qx/locale/translations
  
distclean: clean
realclean: clean
