QOOXDOO = PATH_TO_QOOXDOO
QOOXDOO = ../../../../

NAME = custom
TITLE = CUSTOM
PROJECT_FILES = index.html
SCRIPTNAME = $(NAME).js
APPLICATION = $(NAME).Application
ALL_CLASSES = true
OPTIMIZE_STRINGS = true
OPTIMIZE_VARIABLES = true
FRAMEWORK_RESOURCES = true
CUSTOM_RESOURCES = true
INTERFACE_INIT = true
NICE = 10

include $(QOOXDOO)/frontend/framework/tool/make/skeleton.mk
