all:
	@../tools/generate/generate.py \
	  --script-input resources/script/source \
	  --script-input ../source/script \
	  --generate-compiled-script \
	  --compiled-script-file resources/script/build/api.js
