#!/bin/sh -vx

#
# This pre-commit hook can work when you use `git add` if you run this command:
#
#   git config core.hooksPath .github/hooks
#
#

FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep '^source/class' | grep '.js$' | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo $FILES
echo "$FILES" | xargs qx es6ify

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0
