/* ************************************************************************

   qooxdoo - the new era of web development

   http://qooxdoo.org

   License:
     MIT: https://opensource.org/licenses/MIT
     See the LICENSE file in the project's top-level directory for details.

************************************************************************ */
/**
 * NOTE: This is automatically generated by bootstrap-compiler.js
*/
qx.Class.define("qx.tool.compiler.Version", {
  extend: qx.core.Object,
  statics: {
    VERSION: "7.0.0-beta"
  }
});
