#!/bin/bash
#
# This builds the new v6 website documentation and apps
#

set -o errexit -o nounset

exe() { echo "\$ ${@/eval/}" ; "$@" ; }

TARGET=deploy/$(cat ./version.txt)
mkdir -p $TARGET

npm i --no-save @qooxdoo/compiler

# build apps (unless already built) & copy to website target
exe npx qx compile compile.json --target build  --feedback=0 --verbose
# run twice for scss compile
exe npx qx compile compile.json --target build  --feedback=0 --verbose
exe cp -a ./apps $TARGET

exe find $TARGET -type f -name '*.map' -delete
exe find $TARGET -type f -name '.*' -delete
exe rm -rf $TARGET/transpiled

# copy documentation
exe cp -a ./docs $TARGET/
