#!/bin/bash
#
# This builds the new v6 website documentation and apps
#

set -o errexit -o nounset

exe() { echo "\$ ${@/eval/}" ; "$@" ; }

TARGET=deploy/$(cat ./version.txt)
mkdir -p $TARGET

exe npm i --no-save @adobe/jsonschema2md@3.3.1 @qooxdoo/compiler mkdirp@^1.0.0

# build apps  
exe npx qx pkg upgrade --prereleases
exe npx qx compile compile.json --target build  --feedback=0 --verbose
#restore .npmignore 
exe git checkout .
# copy to website target
exe rsync -avR ./apps $TARGET --exclude-from=./apps/.npmignore
# copy documentation
exe cp -a ./docs $TARGET/
#build schema docs
exe wget -O $TARGET/docs/compiler/configuration/compile-1-0-0.json https://raw.githubusercontent.com/qooxdoo/qooxdoo-compiler/master/source/resource/qx/tool/schema/compile-1-0-0.json 
exe npx  jsonschema2md -d $TARGET/docs/compiler/configuration/compile-1-0-0.json -o $TARGET/docs/compiler/configuration