#!/usr/bin/env bash
# returns 1 if the commits contain only documentation (=markdown files)
# ans 0 if not. prints the names of all markdown files to stdout
git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
git fetch -q
CHANGED_FILES=`git diff --name-only HEAD origin/master`
CONTAINS_MD=False
CONTAINS_CODE=False
MARKDOWN_FILES=""
MD=".md"

for CHANGED_FILE in $CHANGED_FILES; do
  if [[ $CHANGED_FILE =~ $MD ]]; then
    CONTAINS_MD=True
    MARKDOWN_FILES="$MARKDOWN_FILES $CHANGED_FILE"
  else
    CONTAINS_CODE=True
  fi
done
echo $MARKDOWN_FILES

if [[ $CONTAINS_MD == True ]] && [[ $CONTAINS_CODE == False ]]; then
  exit 1
fi
exit 0
