#!/bin/sh
export PATH=$PWD/node_modules/karma/bin:$PATH
export DISPLAY=:99.0
sh -e /etc/init.d/xvfb start

php -S 0.0.0.0:31323 &> /dev/null &
./generate.py -sI test-source -m TEST_TRAVIS:true

karma start --reporters=dots,coverage,coveralls karma-coverage.conf.js --hostname="$(hostname)"
RET=$?

pkill -f 'php -S 0.0.0.0:31323' &> /dev/null
exit $RET

