#!/bin/bash
set -o errexit -o nounset

cd $TRAVIS_BUILD_DIR

TARGET="devel"
MASTER="master"
CURRENT=0

rev=$(git rev-parse --short HEAD)
mkdir deploy && cd deploy

git init
git config user.name "Travis CI deploy"
git config user.email "no-reply@qooxdoo.org"
git config push.default simple

GIT_IO_URL="https://$GH_TOKEN@github.com/qooxdoo/qooxdoo.github.io.git"
git remote add upstream $GIT_IO_URL
git fetch --depth 10 upstream
git merge upstream/master

# Adjust settings for TAG build
if [ "$TRAVIS_TAG" != "" ]; then
  RELEASE=${TRAVIS_TAG#release_}
  TARGET=${RELEASE//_/.}
  LAST_VERSION=$(ls -1d [0-9]* | sort -V | tail -n1)

  if dpkg --compare-versions "$TARGET" "gt" "$LAST_VERSION"; then
    CURRENT=1
  fi
fi

cd $TRAVIS_BUILD_DIR
.travis/build-site
.travis/build-site-v6

cd deploy
rm -rf "$TARGET" &> /dev/null
cp -a ../build "$TARGET"

# Maintain the current link
if [ $CURRENT = 1 ]; then
  rm -f current
  ln -s "$TARGET" current
fi
# global /docs shows documentation of current master
rm -f docs                              
ln -s $(cat ../version.txt)/docs docs
# global /apps shows apps of current master, needed for /docs
rm -f apps                             
ln -s $(cat ../version.txt)/apps apps

touch .nojekyll
touch .

git add -A .
git commit -m "Refresh site at ${rev}"
git push -q upstream HEAD:master

# Do a regular checkout and make a dummy commit
git clone --depth 10 -q $GIT_IO_URL tmp
cd tmp
echo $rev > revision
git add revision
git commit -m "Dummy commit to fix github site sync"
git push -q
