#!/bin/bash

set -o errexit -o nounset

exe() { echo "\$ ${@/eval/}" ; "$@" ; }

cd ${TRAVIS_BUILD_DIR:-.}


BASE_DIR="$(git rev-parse --show-toplevel)"
FRAMEWORK_VERSION=$(cat $BASE_DIR/version.txt)
TAG_VERSION="$FRAMEWORK_VERSION"
REV=$(git rev-parse --short HEAD)
FRAMEWORK_DATE=$(date +%Y%m%d-%H%M)

# Adjust the framework version for non TAG builds
if [ "${TRAVIS_TAG:-}" = "" ]; then
   TAG_VERSION="$TAG_VERSION-$FRAMEWORK_DATE"
fi

echo "-------------------------------------------------------------------------"
echo "Travis Tag       : ${TRAVIS_TAG:-}"
echo "Framework version: $FRAMEWORK_VERSION"
echo "Revision         : $REV"
echo "Tag version      : $TAG_VERSION"
echo "TRAVIS_BUILD_DIR : ${TRAVIS_BUILD_DIR:-.}"
echo "Build source     : $BASE_DIR"
echo "-------------------------------------------------------------------------"

cd $BASE_DIR
if [ "{TRAVIS_TAG:-}" != "$FRAMEWORK_VERSION" ]; then
    echo "Bump version ..."
    exe tool/admin/bin/bumpqxversion.py $TAG_VERSION
fi

exe node -v
exe npm  -v

echo ">>> Installing dependencies..."
exe npm install

echo ">>> Installing github.com/qooxdoo/qooxdoo-compiler"
exe [ -d ./qooxdoo-compiler ] && exe rm -rf ./qooxdoo-compiler
exe git clone https://github.com/qooxdoo/qooxdoo-compiler.git --depth=1 --single-branch ./qooxdoo-compiler
exe cd ./qooxdoo-compiler
exe npm install
QX=`pwd`/qx
exe cd ..
exe $QX --version

echo ">>> Compiling & deploying server library with the compiler master using current qx_server library from NPM..."
exe $QX compile --config-file=compile-server.json --target=build
exe mkdir -p ./lib
exe rm -rf ./lib/*
exe cp -R compiled/build/qx_server ./lib

echo ">>> Compiling & deploying server library with compiler master using the newly built qx_server library..."
exe rm -rf ./qooxdoo-compiler/node_modules/@qooxdoo/framework/lib
exe cp -fR lib ./qooxdoo-compiler/node_modules/@qooxdoo/framework
exe cp -f package.json Manifest.json ./qooxdoo-compiler/node_modules/@qooxdoo/framework
exe rm -rf compiled
exe $QX compile --config-file=compile-server.json --target=build
exe $QX deploy --config-file=compile-server.json

echo ">>> Compiling & deploying API Viewer..."
exe $QX compile --config-file=compile.json --target=build
exe $QX deploy --config-file=compile.json

echo ">>> Deploying Qooxdoo source"
exe mkdir -p source
exe rm -rf ./source/*
exe cp -rf ./framework/source/* ./source

# we're not deploying anything, just testing
# exit 0;


echo ">>> Publishing to NPM"
# fill .npmrc with access token
echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN:-}" > ~/.npmrc
exe npm publish --access public




