#!/bin/bash

exe() { echo "\$ ${@/eval/}" ; "$@" ; }

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
exe ~/.nvm/nvm.sh --version
exe ~/.nvm/nvm.sh install lts
exe ~/.nvm/nvm.sh use lts

exe npm i -g npm
exe node -v
exe npm  -v

files=$(find . -name package.json -print | grep -v node_modules | sort)

for f in ${files}; do
    dir=$(dirname $f)
    echo "Installing ${dir} "
    (cd ${dir} && npm install )
done