#!/usr/bin/env python

################################################################################
#  qooxdoo - the new era of web development
#
#  http://qooxdoo.org
#
#  Copyright:
#    2007 1&1 Internet AG, Germany, http://www.1and1.org
#
#  License:
#    LGPL: http://www.gnu.org/licenses/lgpl.html
#    EPL: http://www.eclipse.org/org/documents/epl-v10.php
#    See the LICENSE file in the project's top-level directory for details.
#
#  Authors:
#    * Thomas Herchenroeder (thron7)
################################################################################

##
#<h2>Module Description</h2>
#<pre>
#
# NAME
#  packer.py -- produce compressed JavaScript code
#
# SYNTAX
#  from qx.compiler.backend.packer import *
#  retcode = output(qx_ast)
#
#  qx_ast -- root node of an abstract syntax tree (qx.compiler.ast)
#
#</pre>
##

##
# Generate compressed JavaScript code from qooxdoo AST.
#
# @param ast qooxdoo Abstract Syntax Tree (as generated by the frontend)

def output(ast):
  pass

