################################################################################
#
#  qooxdoo - the new era of web development
#
#  http://qooxdoo.org
#
#  Copyright:
#    2007 1&1 Internet AG, Germany, http://www.1und1.de
#
#  License:
#    LGPL: http://www.gnu.org/licenses/lgpl.html
#    EPL: http://www.eclipse.org/org/documents/epl-v10.php
#    See the LICENSE file in the project's top-level directory for details.
#
#  Authors:
#    * Fabian Jakobs (fjakobs)
#
################################################################################

####################################################################################
# BASIC SETTINGS
####################################################################################

QOOXDOO_PATH = ../../..
QOOXDOO_URI = ../../../../..
APPLICATION_HTML_TO_ROOT_URI=..

APPLICATION_NAMESPACE = testrunner
APPLICATION_CLASSNAME = TestLoader
APPLICATION_SCRIPT_FILENAME = tests.js

APPLICATION_MAKE_TITLE = TESTS FOR TESTRUNNER
APPLICATION_API_TITLE = qooxdoo Tests

APPLICATION_FILES = html
APPLICATION_LOCALES = C de de_DE fr fr_FR

APPLICATION_PUBLISH_PATH = root@qooxdoo.org:/var/www/qooxdoo/demo/$(FRAMEWORK_VERSION)/$(APPLICATION_NAMESPACE)



####################################################################################
# ADVANCED SETTINGS
####################################################################################

APPLICATION_RESOURCE_FILTER = true

APPLICATION_LINEBREAKS_BUILD = true
APPLICATION_LINEBREAKS_SOURCE = true

APPLICATION_COMPLETE_BUILD = false
APPLICATION_COMPLETE_SOURCE = false
#APPLICATION_ENABLE_GUI = false

APPLICATION_OPTIMIZE_STRINGS = false
APPLICATION_OPTIMIZE_VARIABLES = false
APPLICATION_OPTIMIZE_BROWSER = false

APPLICATION_ADDITIONAL_SOURCE_OPTIONS = \
  --include testrunner.test.*

APPLICATION_ADDITIONAL_BUILD_OPTIONS = $(APPLICATION_ADDITIONAL_SOURCE_OPTIONS)






####################################################################################
# INCLUDE CORE
####################################################################################

ifneq ($(QOOXDOO_PATH),PLEASE_DEFINE_QOOXDOO_PATH)
	include $(QOOXDOO_PATH)/frontend/framework/tool/make/targets.mk
	include $(QOOXDOO_PATH)/frontend/framework/tool/make/application.mk
endif

error:
	@echo "  * Please configure QOOXDOO_PATH"

