name: Check markdown in documentation changes

on:
  pull_request:
    paths:
      - 'docs/**'
jobs:
  check_markdown:
    name: Check markdown in changed files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: .github/workflows/markdown-lint-install
      - id: file_changes
        name: Track file changes
        uses: trilom/file-changes-action@v1.2.4
      - name: Check markdown on changed files
        run: .github/workflows/markdown-lint lint
