name: When a tag is pushed, send it to all repos
on:
  push:
    tags:
      - "*"
    branches:
      - "latest"
      
  workflow_dispatch:
 
jobs:
  provide_repository_names:
    name: Get repo names in ${{ github.repository_owner }}
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'qooxdoo/qooxdoo' }}
    steps:
      - uses: actions/setup-node@v2
      - uses: octokit/graphql-action@v2.x
        id: get_repo_names
        with:
          query: |
            query { search(query: "org:${{ github.repository_owner }}", type: REPOSITORY, first: 100) {
              edges { node { ... on Repository { name } } }
            } }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: transform
        run: |
          node << HEREDOC > data.json
          let d=${{ steps.get_repo_names.outputs.data }};
          d = d.search.edges.map(item=>item.node.name);
          console.log(JSON.stringify(d,null,0));
          HEREDOC
          echo "::set-output name=repos::$(cat data.json)"
    outputs:
      repos: ${{ steps.transform.outputs.repos }}

  debug:
    name: Log needed values for debugging (can be disabled)
    if: ${{ github.repository == 'qooxdoo/qooxdoo' }}
    runs-on: ubuntu-latest
    needs: provide_repository_names
    steps:
      - run: |
          echo "repos: ${{ needs.provide_repository_names.outputs.repos }}"
          echo "ref: ${{ github.ref }}"

  sleep:
    name: Wait for 10 min
    runs-on: ubuntu-latest
    needs: provide_repository_names
    steps:
      - run: |
          sleep 600

  dispatch:
    name: Send repository_dispatch
    continue-on-error: true
    if: ${{ github.repository == 'qooxdoo/qooxdoo' }}
    needs: [provide_repository_names, sleep]
    strategy:
      matrix:
        repo: ${{ fromJson(needs.provide_repository_names.outputs.repos) }}
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPOSITORY_DISPATCH }}
          repository: ${{ github.repository_owner }}/${{ matrix.repo }}
          event-type: "push-tag"
          client-payload: '{ "ref": "${{ github.ref }}" }'
