name: run framework tests

on:
  push:
    paths:
      - 'compile.*'
      - 'source/**'
      - 'test/**'

  pull_request:
    paths:
      - 'compile.*'
      - 'source/**'
      - 'test/**'

jobs:
  test:
    name: run tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [10.x, 12.x, 14.x]

    steps:
      - name: checkout
        uses: actions/checkout@v2


      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: microsoft/playwright-github-action@v1

      - name: install and test
        run:  |
              npm  ci
              npm  test
